INSERT INTO products (
drawing_url,
image_url,
name,
latin_name,
description,
intended_for,
temp, 
water,
height,
sun,
sun_description,
water_description,
price_in_cents,
inventory ) 
VALUES (
'/images/products/draw/1.png',
'/images/products/pics/1p.png',
'Aloe Vera',
'Abies alba',
'Aloe Vera is a succulent plant that is popular for its medicinal and skin-nourishing properties. It makes an excellent gift choice for anyone who values natural remedies and enjoys taking care of plants. Aloe Vera is also easy to care for and can thrive in a range of lighting conditions, making it a great option for both novice and experienced plant owners. In addition, it''s a versatile plant that can be used for a variety of purposes, including treating sunburns, soothing skin irritation, and adding moisture to dry skin. Overall, Aloe Vera is a practical and unique plant that would make a great gift for any occasion.',
ARRAY['values natural remedies and enjoys taking care of plants, as Aloe Vera is a succulent plant with many medicinal properties', 'spends a lot of time outdoors and would appreciate a gift that can help soothe and treat sunburns', 'has a dry skin condition and would benefit from a plant that can add moisture and nourishment to the skin','is a plant lover who enjoys collecting unique and practical plants, as Aloe Vera is a versatile plant that can be used for a variety of purposes'],
'15-25 °C',
'2 / week',
'12-36 in.',
'Full, partial',
'Aloe Vera needs bright, natural light in order to thrive. Outdoors, aim for up to six hours of full sun, with a small shade reprieve in the afternoon. When grown inside, aloe should be placed in a window with bright, indirect sunlight. Direct sun can burn its tender skin, yet lack of light will cause the plant to grow leggy and weaken its leaves, causing them to crease.',
'Aloe prefers to be watered regularly, as long as the soil dries out completely in between waterings. If the soil remains dry for long periods of time, the leaves will shrivel and pucker slightly. The plant will recover when watered, however, extended periods of stress—either prolonged drought or too much water—will make the leaves turn yellow and die. Do not water outdoor plants during periods of rain.\n
Aloe vera goes dormant in the winter and won''t require any water at all, provided it received sufficient water during its growing season. If your climate is rainy during the winter, consider planting aloe in gravel or stones. This will allow the water to run off and prevent rot.',
3295,
12);

INSERT INTO products (
drawing_url,
image_url,
name,
latin_name,
description,
intended_for,
temp, 
water,
height,
sun,
sun_description,
water_description,
price_in_cents,
inventory ) 
VALUES (
'/images/products/draw/2.png',
'/images/products/pics/2p.png',
'Bird of Paradise',
'Strelitzia reginae',
'The Bird of Paradise flower is a striking tropical plant known for its bright orange and blue blooms that resemble a bird''s head. It''s a great gift choice for plant lovers who appreciate exotic and resilient plants that can bloom for months at a time. The plant symbolizes joy, freedom, and paradise, making it a thoughtful and heartfelt gift for any occasion.',
ARRAY['loves tropical plants and wants to add a unique and eye-catching flower to their collection', 'recently moved into a new home and wants to add a touch of tropical beauty to their space', 'is celebrating a special occasion, such as a birthday or anniversary', 's recovering from an illness or injury and would benefit from a colorful and uplifting bouquet of flowers', 'has a passion for gardening and enjoys caring for plants, as the Bird of Paradise flower is a resilient plant that can bloom for months with proper care'],
'15-25 °C',
'7 / week',
'3.5-6 ft.',
'Full, partial',
'This plant needs bright light, including some direct sunlight, to bloom well. However, it requires shielding in the direct midday summer sun, which can burn the leaves of younger plants. A good position is in a room with windows facing east or west. Avoid rooms with only a north-facing window.',
'Keep the soil continually moist throughout the year. While it should not be waterlogged, expect to water it daily in the spring and summer as it loses moisture through its big leaves. You can water it until you see the water draining from its drainage holes, but make sure it does not sit in a pool of water. If overwatered, the plant will develop crunchy brown leaves. If underwatered, the leaves farthest from the center will turn yellow.',
2895,
12);

INSERT INTO products (
drawing_url,
image_url,
name,
latin_name,
description,
intended_for,
temp, 
water,
height,
sun,
sun_description,
water_description,
price_in_cents,
inventory ) 
VALUES (
'/images/products/draw/3.png',
'/images/products/pics/3p.png',
'Anthurium',
'Anthurium spp',
'Anthuriums are a popular and unique tropical plant known for their heart-shaped leaves and vibrant, long-lasting flowers in shades of red, pink, white, and orange. They make an excellent gift choice for anyone who loves plants and enjoys a pop of color in their space. Anthuriums are also known for their air-purifying properties, making them a thoughtful gift for anyone who values a healthy home environment. In addition, they are easy to care for and can thrive in a range of lighting conditions, making them a great option for both novice and experienced plant owners.',
ARRAY['loves colorful and unique plants, as the Anthurium offers a range of vibrant and long-lasting flowers in various shades', 'is environmentally conscious and would appreciate a gift that offers air-purifying properties', 'enjoys caring for plants but has limited space, as Anthuriums are compact and can be grown in a variety of containers', 'who is looking for a gift that will last, as Anthuriums have a long blooming period and can continue to produce flowers with proper care'],
'18-30 °C',
'3-4 / week',
'12-18 in.',
'Partial',
'Anthurium plants thrive in bright, indirect light, and they do not like exposure to direct sunlight, except in the winter months or in plants that have been carefully acclimated. Wild anthuriums generally live in temperatures at or above 60 degrees Fahrenheit, and the foliage types prefer temperatures even warmer. If temperatures dip below this level, the plant will suffer.',
'The soil should be kept slightly moist and never allowed to dry out completely. Set the pot in a tray with rocks or gravel that has water. The plant''s water can drain there and help keep humidity levels higher around the plant. Allow the top of the soil to dry out to the touch before watering again. Indoors, this is about once a week. If outside, during hot days, it can be every two or three days between waterings.',
2295,
12);

INSERT INTO products (
drawing_url,
image_url,
name,
latin_name,
description,
intended_for,
temp, 
water,
height,
sun,
sun_description,
water_description,
price_in_cents,
inventory ) 
VALUES (
'/images/products/draw/4.png',
'/images/products/pics/4p.png',
'Money Tree',
'Pachira aquatica',
'The Money Tree is a popular indoor plant known for its unique braided trunk and coin-shaped leaves. It makes an excellent gift choice for anyone who loves plants and enjoys a touch of whimsy in their decor. In addition to its aesthetic appeal, the Money Tree is believed to bring good luck and prosperity, making it a thoughtful gift for anyone who could use a little extra positivity in their life. Money Trees are also easy to care for and can thrive in a variety of lighting conditions, making them a great option for both novice and experienced plant owners.',
ARRAY['is looking for a unique and meaningful gift, as the Money Tree is believed to bring good luck and prosperity', 'loves plants and enjoys adding a touch of whimsy to their decor', 'is a novice plant owner who wants a low-maintenance plant that is easy to care for, as the Money Tree is a hardy plant', 'is starting a new business or embarking on a new career path and could use a little extra positivity and good luck'],
'15-25 °C',
'1 / week',
'6-8 ft.',
'Full, partial',
'Outdoors, these plants can tolerate direct sunlight, but indoors money trees need specific light requirements. They should be placed in bright to medium indirect sunlight, for at least six hours a day.\n
If you don''t have a sunny window that provides enough light, this plant will also do well under fluorescent light.',
'Money trees should be watered often and regularly, each time the top inch of soil is dry. Typically watering money trees should become more frequent in the spring and summer months and less frequent in the fall and winter. While money trees thrive with lots of water, be careful not to overwater them, as doing so can quickly kill them. The best way to avoid overwatering your plant is to ensure that the potting container and the soil have the proper drainage.',
3495,
12);

INSERT INTO products (
drawing_url,
image_url,
name,
latin_name,
description,
intended_for,
temp, 
water,
height,
sun,
sun_description,
water_description,
price_in_cents,
inventory ) 
VALUES (
'/images/products/draw/5.png',
'/images/products/pics/5p.png',
'Dragon Tree',
'Dracaena draco',
'The Dragon Tree is a striking indoor plant with a unique, sculptural appearance that is sure to make a statement in any space. It makes an excellent gift choice for anyone who loves plants and appreciates a touch of drama in their decor. In addition to its aesthetic appeal, the Dragon Tree is known for its air-purifying qualities, making it a great choice for anyone who values clean air and a healthy living environment. Dragon Trees are also easy to care for and can thrive in a variety of lighting conditions, making them a great option for both novice and experienced plant owners.',
ARRAY['appreciates unique and striking decor, as the Dragon Tree has a sculptural appearance that is sure to make a statement in any space', 'values clean air and wants to improve the air quality in their home or office, as the Dragon Tree is known for its air-purifying qualities', 'is a plant lover who enjoys collecting unique and interesting plants, as the Dragon Tree has a distinct appearance', 'is a novice plant owner who wants a low-maintenance plant that is easy to care for, as the Dragon Tree is a hardy plant that can thrive in a variety of lighting conditions'],
'15-25 °C',
'2 / week',
'3-4 ft.',
'Full sun',
'This plant likes to grow in relatively bright light, but it may resent being in full harsh afternoon sun. Indoor plants will do best in a location that gets a full 10 hours of bright but indirect light.',
'Allow the plants to dry between waterings, but not completely. These plants are more susceptible to root rot, so be very careful never to allow them to sit in standing water.',
3295,
12);

INSERT INTO products (
drawing_url,
image_url,
name,
latin_name,
description,
intended_for,
temp, 
water,
height,
sun,
sun_description,
water_description,
price_in_cents,
inventory ) 
VALUES (
'/images/products/draw/6.png',
'/images/products/pics/6p.png',
'Amaryllis',
'Hippeastrum',
'Amaryllis is a popular flowering plant known for its showy, trumpet-shaped blooms in shades of red, pink, white, and other colors. It makes an excellent gift choice for anyone who loves plants and enjoys the beauty of fresh flowers. In addition to its aesthetic appeal, the Amaryllis is easy to care for and can bloom multiple times per year, making it a great choice for anyone who wants a long-lasting gift. Amaryllis bulbs can also be forced to bloom during the winter months, adding a splash of color and cheer to an otherwise dreary season.',
ARRAY['loves fresh flowers and wants a long-lasting gift that will continue to bloom and bring joy throughout the year', 'is an experienced gardener who enjoys growing and caring for flowering plants, as the Amaryllis is easy to care for and can be grown indoors or outdoors', 'lives in a colder climate and wants to add a splash of color and cheer to the winter months, as the Amaryllis can be forced to bloom indoors during the winter', 'enjoys decorating their home with plants and flowers, as the Amaryllis has a showy and dramatic appearance that can add a touch of elegance to any room'],
'12-15 °C',
'3-4 / week',
'1-2 ft.',
'Full, partial',
'Grown as a potted plant indoors, amaryllis prefers direct morning sun but bright indirect light in the afternoon. Keep the soil moist but not wet. A thick flower stalk should shoot up within a few weeks after planting. The flat leaves will follow as the flower stalk matures. Turn the pot every few days, so the flower stalk receives uniform sunlight exposure on all sides and grows straight.',
'Water your amaryllis whenever the top two inches of soil becomes dry. And, feed it with a half-strength water-soluble fertilizer every two to three weeks.',
2295,
12);